#define TK_SEMI                            1
#define TK_EXPLAIN                         2
#define TK_QUERY                           3
#define TK_PLAN                            4
#define TK_BEGIN                           5
#define TK_TRANSACTION                     6
#define TK_DEFERRED                        7
#define TK_IMMEDIATE                       8
#define TK_EXCLUSIVE                       9
#define TK_COMMIT                         10
#define TK_END                            11
#define TK_ROLLBACK                       12
#define TK_SAVEPOINT                      13
#define TK_RELEASE                        14
#define TK_TO                             15
#define TK_CREATE                         16
#define TK_TABLE                          17
#define TK_IF                             18
#define TK_NOT                            19
#define TK_EXISTS                         20
#define TK_TEMP                           21
#define TK_LP                             22
#define TK_RP                             23
#define TK_AS                             24
#define TK_COMMA                          25
#define TK_ID                             26
#define TK_ABORT                          27
#define TK_AFTER                          28
#define TK_ANALYZE                        29
#define TK_ASC                            30
#define TK_ATTACH                         31
#define TK_BEFORE                         32
#define TK_CASCADE                        33
#define TK_CAST                           34
#define TK_CONFLICT                       35
#define TK_DATABASE                       36
#define TK_DESC                           37
#define TK_DETACH                         38
#define TK_EACH                           39
#define TK_FAIL                           40
#define TK_FOR                            41
#define TK_IGNORE                         42
#define TK_INITIALLY                      43
#define TK_INSTEAD                        44
#define TK_LIKE_KW                        45
#define TK_MATCH                          46
#define TK_KEY                            47
#define TK_OF                             48
#define TK_OFFSET                         49
#define TK_PRAGMA                         50
#define TK_RAISE                          51
#define TK_REPLACE                        52
#define TK_RESTRICT                       53
#define TK_ROW                            54
#define TK_TRIGGER                        55
#define TK_VACUUM                         56
#define TK_VIEW                           57
#define TK_VIRTUAL                        58
#define TK_REINDEX                        59
#define TK_RENAME                         60
#define TK_CTIME_KW                       61
#define TK_ANY                            62
#define TK_OR                             63
#define TK_AND                            64
#define TK_IS                             65
#define TK_BETWEEN                        66
#define TK_IN                             67
#define TK_ISNULL                         68
#define TK_NOTNULL                        69
#define TK_NE                             70
#define TK_EQ                             71
#define TK_GT                             72
#define TK_LE                             73
#define TK_LT                             74
#define TK_GE                             75
#define TK_ESCAPE                         76
#define TK_BITAND                         77
#define TK_BITOR                          78
#define TK_LSHIFT                         79
#define TK_RSHIFT                         80
#define TK_PLUS                           81
#define TK_MINUS                          82
#define TK_STAR                           83
#define TK_SLASH                          84
#define TK_REM                            85
#define TK_CONCAT                         86
#define TK_COLLATE                        87
#define TK_UMINUS                         88
#define TK_UPLUS                          89
#define TK_BITNOT                         90
#define TK_STRING                         91
#define TK_JOIN_KW                        92
#define TK_CONSTRAINT                     93
#define TK_DEFAULT                        94
#define TK_NULL                           95
#define TK_PRIMARY                        96
#define TK_UNIQUE                         97
#define TK_CHECK                          98
#define TK_REFERENCES                     99
#define TK_AUTOINCR                       100
#define TK_ON                             101
#define TK_DELETE                         102
#define TK_UPDATE                         103
#define TK_INSERT                         104
#define TK_SET                            105
#define TK_DEFERRABLE                     106
#define TK_FOREIGN                        107
#define TK_DROP                           108
#define TK_UNION                          109
#define TK_ALL                            110
#define TK_EXCEPT                         111
#define TK_INTERSECT                      112
#define TK_SELECT                         113
#define TK_DISTINCT                       114
#define TK_DOT                            115
#define TK_FROM                           116
#define TK_JOIN                           117
#define TK_INDEXED                        118
#define TK_BY                             119
#define TK_USING                          120
#define TK_ORDER                          121
#define TK_GROUP                          122
#define TK_HAVING                         123
#define TK_LIMIT                          124
#define TK_WHERE                          125
#define TK_INTO                           126
#define TK_VALUES                         127
#define TK_INTEGER                        128
#define TK_FLOAT                          129
#define TK_BLOB                           130
#define TK_REGISTER                       131
#define TK_VARIABLE                       132
#define TK_CASE                           133
#define TK_WHEN                           134
#define TK_THEN                           135
#define TK_ELSE                           136
#define TK_INDEX                          137
#define TK_ALTER                          138
#define TK_ADD                            139
#define TK_COLUMNKW                       140
#define TK_TO_TEXT                        141
#define TK_TO_BLOB                        142
#define TK_TO_NUMERIC                     143
#define TK_TO_INT                         144
#define TK_TO_REAL                        145
#define TK_END_OF_FILE                    146
#define TK_ILLEGAL                        147
#define TK_SPACE                          148
#define TK_UNCLOSED_STRING                149
#define TK_FUNCTION                       150
#define TK_COLUMN                         151
#define TK_AGG_FUNCTION                   152
#define TK_AGG_COLUMN                     153
#define TK_CONST_FUNC                     154
